# Generated by Django 2.2.2 on 2019-07-21 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('HOD', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='myimages')),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('semester', models.CharField(blank=True, choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('fifth', 'Fifth'), ('sixth', 'Sixth'), ('seventh', 'Seventh'), ('eigth', 'Eigth')], max_length=20, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Departments')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='PdfFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='notes/myfiles')),
                ('image', models.ImageField(blank=True, null=True, upload_to='myimages')),
                ('term', models.CharField(blank=True, choices=[('minor1', 'minor1'), ('minor2', 'minor2'), ('major', 'major')], max_length=20, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Subject')),
            ],
            options={
                'verbose_name_plural': 'Pdffiles',
            },
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Departments')),
                ('files', models.ManyToManyField(to='papers.PdfFiles')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Subject')),
            ],
            options={
                'verbose_name_plural': 'Papers',
            },
        ),
    ]
