# Generated by Django 2.2.2 on 2019-06-28 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('HOD', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Departments')),
            ],
            options={
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='PdfFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='myfiles')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Subject')),
            ],
            options={
                'verbose_name_plural': 'Pdffiles',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth')], max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Departments')),
                ('files', models.ManyToManyField(to='notes.PdfFiles')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Subject')),
            ],
            options={
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
