# Generated by Django 2.2.2 on 2019-06-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffiles',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='notes/myfiles'),
        ),
    ]
