# Generated by Django 2.2.2 on 2019-06-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190629_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffiles',
            name='image',
            field=models.ImageField(default=1, upload_to='myimages'),
        ),
    ]
