# Generated by Django 2.2.2 on 2019-07-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_pdffiles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffiles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='myimages'),
        ),
    ]
