# Generated by Django 2.2.2 on 2019-07-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20190702_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='myimages'),
        ),
    ]
