# Generated by Django 2.2.2 on 2019-07-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20190721_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffiles',
            name='term',
            field=models.CharField(blank=True, choices=[('minor1', 'minor1'), ('minor2', 'minor2'), ('major', 'major')], max_length=20, null=True),
        ),
    ]
