# Generated by Django 2.2.2 on 2019-07-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_pdffiles_term'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
