# Generated by Django 2.2.2 on 2019-07-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_delete_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffiles',
            name='files',
            field=models.FileField(default=1, upload_to='notes/myfiles'),
        ),
        migrations.AlterField(
            model_name='pdffiles',
            name='term',
            field=models.CharField(choices=[('minor1', 'minor1'), ('minor2', 'minor2'), ('major', 'major')], default=1, max_length=20),
        ),
    ]
