# Generated by Django 2.2.2 on 2019-07-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_remove_pdffiles_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.TextField(editable=False, max_length=20)),
            ],
        ),
    ]
