# Generated by Django 2.2.2 on 2019-07-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_auto_20190729_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffiles',
            name='added_by_name',
            field=models.TextField(default=1, editable=False, max_length=20),
        ),
    ]
